### ISSUE TITLE
JS script to get a RSS feed

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-Web#15]
all you have to do is create the script and print it to the debugger, I will implement with other features later.

**Comment by swarupe** [comment]
Can you explain the functionality of it?

**Comment by FultonBrowne** [comment]
As of this time, get the rss feed, convert it to a js object, and print he content to the debugger.

**Comment by swarupe** [comment]
What type of feed? Can you share the feed URL?

**Comment by FultonBrowne** [comment]
It just a generic RSS 2.0 feed, here is the link https://araserver.herokuapp.com/

**Comment by swarupe** [comment]
RSS feeds give xml output right? So we need to parse the XML and return a JSON object if I am correct, but the above link is not giving XML

**Comment by FultonBrowne** [comment]
check your debugger, its xml.

**Comment by swarupe** [comment]
The above URL i am not able to read from fetch API because of CORS so I will be using some random RSS feed. I am using jQuery to parse the XML document and produce the JSON object, is that Ok?

**Comment by FultonBrowne** [comment]
Yes @swarupe , thats great
