### ISSUE TITLE
Make a basic ui for testing

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-Web#7]
I have almost no web dev experience, so if you can give it a similar ui to Ara android that would be awesome.

**Comment by SP-2605** [comment]
Hi! What kind of design would you like to have? And what content must be present in the website?

**Comment by FultonBrowne** [comment]
I am looking for a similar  ui to ara for android, as far as content there is a main feed that adds and changes content based on user preferences, selections, and searches. for now just a basic nav drawer that switches content will be fine though :)
![image](https://user-images.githubusercontent.com/50185337/67015415-56551080-f0ab-11e9-93e4-940f632a3f21.png)

**Comment by vikasprashar99** [comment]
i have updated the UI
